[ssi_timesheet_attendance]14.0.1.0.0
open-synergy/opnsynid-hr-timesheet pull request #2
Opened 2022-06-11 15:07 UTC by azmimr67

* Pembuatan Modul Baru
* Migrasi dari veersi 8

2022-06-14 09:41 UTC, andhit-r requested changes
@azmimr67 Tolong diubah dulu yah

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/__manifest__.py
> +        "ssi_hr",
Tidak perlu krn ssi_timesheet sudah depend ke sini

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/views/hr_attendance_reason_views.xml
> +        name="Attendance Reason"
Attendance Reasons. Menu dengan action yang membuka master data atau transaksi selalu diberi nama dengan bentuk plural

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +    _order = "check_in"
date, check_in

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +                ("date_end", ">=", record.date),
Ditambahkan yang statusnya masih open

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +        compute="_compute_sheet",
ditambahkan parameter:
* store=True
* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +        store=True,
Ditambahkan parameter:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +        default=lambda self: self._default_employee_id(),
Ditambahkan param:

* required=True
* ondelete="restrict"

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +    )
Ditambahkan param:

* ondelete="restrict"

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +    )
Ditambahkan param:

* ondelete="restrict"

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance.py
> +            attn.date = fields.Datetime.context_timestamp(self, attn.check_in)
Dibuang krn tidak digunakan

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    _rec_name = "id"
sheet_id, date

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +        for record in self:
Berikan nilai apabila record.date_start tidak mempunyai nilai

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    @api.depends("date_start")
date, employee_id

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +            real_date_end = False
```suggestion
            real_date_start = real_date_end = False
```

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +            len(attendances)
Buang

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-14 09:41 UTC, andhit-r commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    )
Ditambahkan param:

* compute_sudo=True

2022-06-15 05:04 UTC, azmimr67 commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    _rec_name = "id"
Yang dimaksud ini
_rec_name = "sheet_id,date"

atau
_order = "sheet_id,date"

2022-06-15 05:25 UTC, azmimr67 commented on ssi_timesheet_attendance/models/hr_timesheet_attendance_schedule.py
> +    _rec_name = "id"
atau buat method name_get ? sebab ada 2 field

2022-06-16 03:26 UTC, merged